### PR TITLE
Added simple cmakefile

### PR DESCRIPTION
**Pull request by diogoalmeida**
Allows for compiling the project in Linux. Note that I modified the gitignore file.

### CODE REVIEW

**Comment by diogoalmeida** [comment]
OBS: In the future, please test the commit before merging.

**Comment by davidalbertonogueira** [comment]
Such is the behaviour for pull requests. 
But this is not a merge with changes in functionality.
As it only adds Linux support, it was promptly accepted.

**Comment by diogoalmeida** [comment]
Ok. Please test before merging in the future.

Regards

**Comment by davidalbertonogueira** [comment]
Sure. All code-related commits will be tested. A previous successful test from the requester is expected, and corresponding unit tests would be appreciated.
But for simple commits like this you can push directly to master branch.

Best regards.

**Pull request merged**
